version: "3.9"

services:
  app:
    build: .
    container_name: ai-service
    ports:
      - "8081:8080"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - microservices-net  # <--- 1. Подключаем сервис к сети

networks:
  microservices-net:       # <--- 2. Объявляем сеть
    external: true